export { ThemeProvider, useTheme, type Theme } from './theme.js';
export { Button, Input, Textarea, Select, Dialog, Tooltip } from './primitives.js';
export { ToastProvider, useToast } from './toast.js';
export { CommandPalette, filterCommands, fuzzyMatch, type PaletteCommand } from './palette.js';
// Icons: single import point so the app stays consistent (F076)
export {
  BookOpen,
  FileText,
  Network,
  CalendarDays,
  Search,
  Settings,
  Settings2,
  Moon,
  Sun,
  Plus,
  X,
  Check,
  ChevronRight,
  // Markdown editor toolbar + preview (Day 2, F123/F138/F139)
  Bold,
  Italic,
  Heading,
  List,
  ListOrdered,
  Code,
  Quote,
  Link2,
  ImagePlus,
  Eye,
  Pencil,
  Columns2,
  WrapText,
  TableOfContents as TocIcon,
  // Notes core UI (Day 2, F141–F199)
  Archive,
  ArchiveRestore,
  ArrowUpDown,
  ChevronDown,
  ClipboardCopy,
  Copy,
  Download,
  FilePlus2,
  // Day 3: query bar, embeds, import UI (F278–F297)
  AlertTriangle,
  RefreshCw,
  Upload,
  // Day 3: graph, journal, templates (F241–F270)
  Flame,
  Folder,
  FolderOpen,
  FolderPlus,
  History,
  Info,
  Keyboard,
  Maximize2,
  Minimize2,
  MoreHorizontal,
  Paperclip,
  Pin,
  PinOff,
  RotateCcw,
  Tag as TagIcon,
  Trash2,
  // Day 6: story authoring workspace (F511–F540)
  FileCode2,
  Play,
  Regex,
  Smartphone,
  Wand2,
  // Day 6: story player + library (F541–F600)
  BarChart3,
  Bookmark,
  GitCompare,
  LogOut,
  Menu,
  Printer,
  Save,
  ScrollText,
  Share2,
  Square,
  Volume2,
  // Day 7: entities, codex, lore & annotations (F601–F700)
  BookMarked,
  Compass,
  Flag,
  Highlighter,
  MapPin,
  Package,
  Shapes,
  Sparkles,
  Users,
} from 'lucide-react';
