export { ThemeProvider, useTheme, type Theme } from './theme.js';
export { Button, Input, Textarea, Select, Dialog, Tooltip } from './primitives.js';
export { ToastProvider, useToast } from './toast.js';
export { CommandPalette, filterCommands, fuzzyMatch, type PaletteCommand } from './palette.js';
// Design-system computational core (Epic 21) — namespaced to avoid collisions.
export * as design from './design/index.js';
// Icons: single import point so the app stays consistent (F076)
export {
  BookOpen,
  FileText,
  Network,
  CalendarDays,
  Search,
  Settings,
  Settings2,
  Moon,
  Sun,
  Plus,
  X,
  Check,
  ChevronRight,
  // Markdown editor toolbar + preview (Day 2, F123/F138/F139)
  Bold,
  Italic,
  Heading,
  List,
  ListOrdered,
  Code,
  Quote,
  Link2,
  ImagePlus,
  Eye,
  Pencil,
  Columns2,
  WrapText,
  TableOfContents as TocIcon,
  // Notes core UI (Day 2, F141–F199)
  Archive,
  ArchiveRestore,
  ArrowUpDown,
  ChevronDown,
  ClipboardCopy,
  Copy,
  Download,
  FilePlus2,
  // Day 3: query bar, embeds, import UI (F278–F297)
  AlertTriangle,
  RefreshCw,
  Upload,
  // Day 3: graph, journal, templates (F241–F270)
  Flame,
  Folder,
  FolderOpen,
  FolderPlus,
  History,
  Info,
  Keyboard,
  Maximize2,
  Minimize2,
  MoreHorizontal,
  Paperclip,
  Pin,
  PinOff,
  RotateCcw,
  Tag as TagIcon,
  Trash2,
  // Day 6: story authoring workspace (F511–F540)
  FileCode2,
  Play,
  Regex,
  Smartphone,
  Wand2,
  // Day 6: story player + library (F541–F600)
  BarChart3,
  Bookmark,
  GitCompare,
  LogOut,
  Menu,
  Printer,
  Save,
  ScrollText,
  Share2,
  Square,
  Volume2,
  // Day 7: entities, codex, lore & annotations (F601–F700)
  BookMarked,
  Compass,
  Flag,
  Highlighter,
  MapPin,
  Package,
  Shapes,
  Sparkles,
  Users,
  // Day 8: search & intelligence (F711–F720, F751–F760, F791–F800)
  Activity,
  AlertCircle,
  BarChart2,
  Brain,
  ChevronLeft,
  CircleCheck,
  ExternalLink,
  Filter,
  GitMerge,
  Globe,
  Heart,
  Lightbulb,
  Link,
  ListFilter,
  Loader2,
  RadioTower,
  SlidersHorizontal,
  TrendingUp,
  Unlink,
  Zap,
  // Day 8: ingestion + clipper + voice (F766, F771–F773, F781–F786)
  BookmarkPlus,
  Clipboard,
  FileInput,
  Mic,
  MicOff,
  Pause,
  PauseCircle,
  PlayCircle,
  StopCircle,
  Volume1,
  WifiOff,
  // Epic 11: Plugin & Extension Architecture (F1041–F1090)
  Blocks,
  Puzzle,
  ShieldCheck,
  ShieldAlert,
  Terminal,
  Wrench,
  PackageSearch,
  // Epic 11 Tier 2: Plugin distribution UI (F1091–F1098)
  ArrowDownToLine,
  BadgeCheck,
  PackagePlus,
  PackageX,
  RefreshCcw,
  // Epic 12: Collaboration — comments, history, chat (F1151–F1180)
  MessageSquare,
  GitBranch,
  CheckSquare,
  Clock,
  AtSign,
} from 'lucide-react';
